all: directives.pdf bundle.zip

bundle.zip:V: directives.pdf
    zip -r bundle.zip directives.pdf NodeRunnerKeyboard/ java/ javascript/

&.pdf: &.md
    pandoc $stem.md \
    -Vgeometry:margin=1.3in \
    -N --variable linkcolor=blue \
    -o $stem.pdf
